from colorama import Fore, Back, Style

BUFFER_RIGHT = 10
BUFFER_DOWN = 10

MIN_HEIGHT = 20
MIN_WIDTH = 60

BG_COLOR = Back.BLUE
BG_ACCENT_COLOR = Back.BLACK
ACCENT_AMT = 0.01
GND_COLOR = Back.MAGENTA
SKY_COLOR = Back.MAGENTA

GND_HEIGHT = 3
SKY_DEPTH = 3

GRAVITY_Y = 0
GRAVITY_X = 0.3
DRAG_COEFF = 0.06

GAME_SPEED = 1
KEY_FORCE = 3

MANDALORIAN_START_Y = 40