from colorama import Fore, Back, Style

BUFFER_RIGHT = 10
BUFFER_DOWN = 10

MIN_HEIGHT = 20
MIN_WIDTH = 60

BG_COLOR = Back.BLUE
BG_ACCENT_COLOR = Back.BLACK
ACCENT_AMT = 0.01
GND_COLOR = Back.MAGENTA
SKY_COLOR = Back.MAGENTA

# NUM_CLOUDS = 1

ART_BASE_PATH = 'art'
# ART_CLOUD_PATH = 'cloud.txt'

GND_HEIGHT = 3
SKY_DEPTH = 3

GRAVITY_Y = 0
GRAVITY_X = 0.26
DRAG_COEFF = 0.04

GAME_SPEED = 1.5
KEY_FORCE = 2.5

MANDALORIAN_START_Y = 40

MAX_LIVES = 3

MIN_BEAM_DIST_X = 40  # unit: Frames
MIN_BEAM_SIZE = 6
MAX_BEAM_SIZE = 10

MIN_COIN_SIZE = 3
MAX_COIN_SIZE = 5